name: GitHub Actions deployment
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: [self-hosted, gift-runner]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Build the image
        run: |
          env